import type { KeyboardLayout } from '../../model/types'

export const Halo75: KeyboardLayout = [
  [
    { code: 'esc', color: 'mint' },
    { code: 'f1', secondaryCode: 'fn_f1' },
    { code: 'f2', secondaryCode: 'fn_f2' },
    { code: 'f3', secondaryCode: 'fn_f3' },
    { code: 'f4', secondaryCode: 'fn_f4' },
    { code: 'f5', color: 'dark', secondaryCode: 'fn_f5' },
    { code: 'f6', color: 'dark', secondaryCode: 'fn_f6' },
    { code: 'f7', color: 'dark', secondaryCode: 'fn_f7' },
    { code: 'f8', color: 'dark', secondaryCode: 'fn_f8' },
    { code: 'f9', color: 'dark', secondaryCode: 'fn_f9' },
    { code: 'f10', color: 'dark', secondaryCode: 'fn_f10' },
    { code: 'f11', color: 'dark', secondaryCode: 'fn_f11' },
    { code: 'f12', color: 'dark', secondaryCode: 'fn_f12' },
    { code: 'screenshot', color: 'dark' },
    { code: 'del', color: 'dark' },
    { code: 'ins', color: 'dark' }
  ],
  [
    { code: 'grave' },
    { code: 'num1' },
    { code: 'num2' },
    { code: 'num3' },
    { code: 'num4' },
    { code: 'num5' },
    { code: 'num6' },
    { code: 'num7' },
    { code: 'num8' },
    { code: 'num9' },
    { code: 'num0' },
    { code: 'minus' },
    { code: 'equal' },
    { code: 'backspace', color: 'dark', width: 2 },
    { code: 'home', color: 'dark' }
  ],
  [
    { code: 'tab', color: 'dark', width: 1.5 },
    { code: 'q' },
    { code: 'w' },
    { code: 'e' },
    { code: 'r' },
    { code: 't' },
    { code: 'y' },
    { code: 'u' },
    { code: 'i' },
    { code: 'o' },
    { code: 'p' },
    { code: 'lbracket' },
    { code: 'rbracket' },
    { code: 'backslash', width: 1.5 },
    { code: 'end', color: 'dark' }
  ],
  [
    { code: 'capslock', color: 'dark', width: 1.75 },
    { code: 'a' },
    { code: 's' },
    { code: 'd' },
    { code: 'f' },
    { code: 'g' },
    { code: 'h' },
    { code: 'j' },
    { code: 'k' },
    { code: 'l' },
    { code: 'semicolon' },
    { code: 'quote' },
    { code: 'enter', width: 2.25, color: 'orange' },
    { code: 'pgup', color: 'dark' }
  ],
  [
    { code: 'lshift', color: 'dark', width: 2.25 },
    { code: 'z' },
    { code: 'x' },
    { code: 'c' },
    { code: 'v' },
    { code: 'b' },
    { code: 'n' },
    { code: 'm' },
    { code: 'comma' },
    { code: 'period' },
    { code: 'fwdslash' },
    { code: 'rshift', color: 'dark', width: 1.75 },
    { code: 'up', color: 'dark', secondaryCode: 'fn_up' },
    { code: 'pgdn', color: 'dark' }
  ],
  [
    { code: 'lctrl', color: 'dark', width: 1.25 },
    { code: 'lalt', color: 'dark', width: 1.25 },
    { code: 'lmeta', color: 'dark', width: 1.25 },
    { code: 'space', color: 'yellow', width: 6.25 },
    { code: 'rmeta', color: 'dark', width: 1.25 },
    { code: 'fn', color: 'dark', width: 1.25, readonly: true },
    { width: 0.5 },
    { code: 'left', color: 'dark', secondaryCode: 'fn_left' },
    { code: 'down', color: 'dark', secondaryCode: 'fn_down' },
    { code: 'right', color: 'dark', secondaryCode: 'fn_right' }
  ]
]
