
import type { KeyboardLayout } from '../types'

export const Halo96: KeyboardLayout = [
  [
    { code: 'esc', color: 'mint' },
    { code: 'f1' },
    { code: 'f2' },
    { code: 'f3' },
    { code: 'f4' },
    { code: 'f5', color: 'dark' },
    { code: 'f6', color: 'dark' },
    { code: 'f7', color: 'dark' },
    { code: 'f8', color: 'dark' },
    { code: 'f9' },
    { code: 'f10' },
    { code: 'f11' },
    { code: 'f12' },
    { code: 'prntscr', color: 'dark' },
    { code: 'del', color: 'dark' },
    { code: 'home', color: 'dark' },
    { code: 'end', color: 'dark' },
    { code: 'pgup', color: 'dark' },
    { code: 'pgdn', color: 'dark' }
  ],
  [
    { code: '~' },
    { code: '1' },
    { code: '2' },
    { code: '3' },
    { code: '4' },
    { code: '5' },
    { code: '6' },
    { code: '7' },
    { code: '8' },
    { code: '9' },
    { code: '0' },
    { code: '-' },
    { code: '+' },
    { code: 'backspace', color: 'dark', width: 2 },
    { code: 'numlk', color: 'dark' },
    { code: '/', color: 'dark' },
    { code: '×', color: 'dark' },
    { code: '-', color: 'dark' }
  ],
  [
    { code: 'tab', color: 'dark', width: 1.5 },
    { code: 'q' },
    { code: 'w' },
    { code: 'e' },
    { code: 'r' },
    { code: 't' },
    { code: 'y' },
    { code: 'u' },
    { code: 'i' },
    { code: 'o' },
    { code: 'p' },
    { code: '[' },
    { code: ']' },
    { code: '\\', width: 1.5 },
    { code: 'num7' },
    { code: 'num8' },
    { code: 'num9' },
    { code: 'numplus', height: 2, color: 'dark' }
  ],
  [
    { code: 'caps', color: 'dark', width: 1.75 },
    { code: 'a' },
    { code: 's' },
    { code: 'd' },
    { code: 'f' },
    { code: 'g' },
    { code: 'h' },
    { code: 'j' },
    { code: 'k' },
    { code: 'l' },
    { code: ';' },
    { code: '\'' },
    { code: 'enter', width: 2.25, color: 'orange' },
    { code: 'num4' },
    { code: 'num5' },
    { code: 'num6' }
  ],
  [
    { code: 'lshift', color: 'dark', width: 2.25 },
    { code: 'z' },
    { code: 'x' },
    { code: 'c' },
    { code: 'v' },
    { code: 'b' },
    { code: 'n' },
    { code: 'm' },
    { code: '<' },
    { code: '>' },
    { code: '/' },
    { code: 'rshift', color: 'dark', width: 1.75 },
    { code: 'up', color: 'dark' },
    { code: 'num1' },
    { code: 'num2' },
    { code: 'num3' },
    { code: 'numenter', height: 2, color: 'mint' }
  ],
  [
    { code: 'lctrl', color: 'dark', width: 1.25 },
    { code: 'option', color: 'dark', width: 1.25 },
    { code: 'lcmd', color: 'dark', width: 1.25 },
    { code: 'space', color: 'yellow', width: 6.25 },
    { code: 'rcmd', color: 'dark', width: 1.25 },
    { code: 'fn', color: 'dark', width: 1.25 },
    { width: 0.5 },
    { code: 'left', color: 'dark' },
    { code: 'down', color: 'dark' },
    { code: 'right', color: 'dark' },
    { code: 'num0' },
    { code: 'numdot' }
  ]
]
