// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {effect} from '../models';
import {keyboard} from '../models';

export function Connect():Promise<string>;

export function GetBacklightModes():Promise<effect.Modes>;

export function GetBacklightState():Promise<keyboard.EffectParams>;

export function GetHaloModes():Promise<effect.Modes>;

export function GetLightState():Promise<keyboard.Effects>;

export function GetSidelightModes():Promise<effect.Modes>;

export function SetBacklight(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetHalo(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetSidelight(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;
