// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function GetBacklightModes() {
  return window['go']['main']['App']['GetBacklightModes']();
}

export function GetBacklightState() {
  return window['go']['main']['App']['GetBacklightState']();
}

export function GetHaloModes() {
  return window['go']['main']['App']['GetHaloModes']();
}

export function GetLightState() {
  return window['go']['main']['App']['GetLightState']();
}

export function GetSidelightModes() {
  return window['go']['main']['App']['GetSidelightModes']();
}

export function SetBacklight(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetBacklight'](arg1, arg2, arg3, arg4);
}

export function SetHalo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetHalo'](arg1, arg2, arg3, arg4);
}

export function SetSidelight(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetSidelight'](arg1, arg2, arg3, arg4);
}
